### ISSUE TITLE
Trade order should allocate storage on ship

### ISSUE THREAD

**Issue by dominik-zeglen** [sectoralphagame/sector-alpha#67]

**Comment by kupka** [comment]
Working on this issue.

**Comment by dominik-zeglen** [comment]
Hey, would you mind getting in touch on discord? I just launched a community server to talk to people and hear their opinion on the game, and to be able to refine features and align priorities better: https://discord.gg/SkDbsUsf

**Comment by kupka** [comment]
I'm not a huge fan of discord to be honest. Any chance of using the GitHub features such as project with issues assignment?

**Comment by dominik-zeglen** [comment]
Sure it is, and the GitHub issues are going to be main source of the things to be done - Discord just provides a platform to talk in real time ;) If you ever change your mind, you're welcome to join there.

**Comment by kupka** [comment]
PR #104 (in progress)

**Comment by dominik-zeglen** [comment]
Fixed in #148
